baseurl = "https://guitton.co/"
title = "guitton.co | python machine learning engineering"
aab = "guitton.co"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

# pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-140255752-1"

[markup.goldmark.renderer]
    unsafe= true

[taxonomies]
    category = "categories"
    series = "series"

[params]
    author = "Louis Guitton"
    info = "Machine Learning Engineer at OneFootball"
    description = "My personal serverless website where I blog and store useful snippets for python software development, machine learning and data engineering."
    keywords = "blog,nlp,machine learning,data engineering,python"
    avatarurl = "images/louis.jpg"

    dateformat = "January 2, 2006"

    favicon_32 = "images/favicon.ico"
    favicon_16 = "images/favicon.ico"

    footercontent = "This website is serverless, check it on <a href='https://github.com/louisguitton/guitton.co' target='_blank'><i class='fab fa-github'></i> Github</a>"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = []

    # for schema.org
    publisher_name = "Guitton.co"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/louisguitton"
[[params.social]]
    name = "Stackoverflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 2
    url = "https://stackoverflow.com/users/3823815/louis-guitton"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/louis_guitton"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://linkedin.com/in/louisguitton/"
[[params.social]]
    name = "Goodreads"
    icon = "fab fa-goodreads"
    weight = 5
    url = "https://goodreads.com/user/show/58757583-louis"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "Freelance"
    weight = 3
    url = "/freelance/"
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "/contact/"
