baseurl = "https://guitton.co/"
title = "guitton.co | python machine learning engineering"
aab = "guitton.co"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

# pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-140255752-1"

# https://gohugo.io/variables/sitemap/
[sitemap]
    filename = "sitemap.xml"

[markup.goldmark.renderer]
    unsafe= true

# https://gohugo.io/variables/taxonomy/
[taxonomies]
    category = "categories"
    series = "series"

# https://gohugo.io/variables/site/
[params]
    author = "Louis Guitton"
    info = "Machine Learning Engineer at OneFootball"
    description = "My personal serverless website where I blog and store useful snippets for python software development, machine learning and data engineering."
    keywords = "blog,nlp,machine learning,data engineering,python"
    avatarurl = "images/louis.jpg"
    images = ["images/guitton_co.png"]  # important for default OpenGraph image

    dateformat = "January 2, 2006"

    favicon_32 = "images/favicon.ico"
    favicon_16 = "images/favicon.ico"

    footercontent = "Made in Berlin 🇩🇪 with <a href='https://gohugo.io/'>Hugo</a>, <a href='https://www.netlify.com/'>Netlify</a> and <a href='https://aws.amazon.com/lambda/'>AWS Lambda</a>"
    hidecredits = true
    hidecopyright = true

    rtl = false

    math = false  # can be overriden for each post
    custom_css = ["css/main.css"]

    # for schema.org
    publisher_name = "Guitton.co"

    googleAnalytics4 = "G-SYZ6E13PWV"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/louisguitton"
[[params.social]]
    name = "Stackoverflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 2
    url = "https://stackoverflow.com/users/3823815/louis-guitton"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/louis_guitton"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://linkedin.com/in/louisguitton/"
[[params.social]]
    name = "Goodreads"
    icon = "fab fa-goodreads"
    weight = 5
    url = "https://goodreads.com/user/show/58757583-louis"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "Freelance"
    weight = 3
    url = "/freelance/"
[[menu.main]]
    name = "Resume"
    weight = 3
    url = "/resume.html"
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "/contact/"
