service: contact # NOTE: update this with your service name

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: python3.7
  stage: development
  region: ${self:custom.secrets.REGION}
  profile: ${self:custom.secrets.PROFILE}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

  environment:
    SENDER_EMAIL: ${self:custom.secrets.SENDER_EMAIL}
    EMAIL_SUBJECT: Serverless Mail
    CONFIG_SET: ConfigSet

functions:
  sendMail:
    handler: handler.sendMail
    description: Send Email using AWS SES Service
    events:
      - http:
          path: sendMail
          method: post
          integration: lambda
          cors: true
          response:
            headers:
              "Access-Control-Allow_Origin": "'*'"
