name: CI

on: [push]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.78.0"
      # we check that hugo can build the site
      # Lighthouse CI can test a static site but I couldn't figure out how to set the port of lhci so that CSS assets load from that basUrl
      - name: Build static website
        run: |
          hugo --gc --minify -b http://localhost

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: run Lighthouse CI
        env:
          HUGO_VERSION: "0.78.0"
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli@0.7.x
          lhci autorun
